[deps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
