[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Distributions = "0.25"
MCMCChains = "5"
Plots = "1"
StatsPlots = "0.14"
Turing = "0.18"
