[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Stheno = "8188c328-b5d6-583d-959b-9690869a5511"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
AbstractGPs = "0.5"
DataFrames = "1"
FillArrays = "0.13"
RDatasets = "0.7"
StatsBase = "0.33"
StatsPlots = "0.14, 0.15"
Stheno = "0.8"
Turing = "0.21, 0.22"
VegaLite = "2"
