[deps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
Bijectors = "0.9.8"
DataFrames = "1"
Distributions = "0.25"
KernelDensity = "0.6"
RDatasets = "0.7"
StatsPlots = "0.14"
Turing = "0.18"
VegaLite = "2.6"
