name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    env:
      # GitHub runners have 2 (modern) cores, so 2-6 threads should be ok.
      # Note that new Julia processes are spawned which also spawn multiple threads.
      JULIA_NUM_THREADS: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'

      - uses: actions/cache@v1
        env:
          cache-name: cache-julia-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}--
            ${{ runner.os }}-test--
            ${{ runner.os }}--

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

      - name: Build only changed tutorials
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: julia --project -e 'using TuringTutorials; build_and_exit(changed_tutorials())'

      - name: Build all tutorials
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: julia --project -e 'using TuringTutorials; build_and_exit(tutorials())'

      - name: Cleanup
        run: |
          rm -rf ClonedTuringTutorials
          # Avoid the github-pages-deploy-action ignoring artifacts.
          rm .gitignore

      - name: Write output to secondary branch
        if: ${{ github.event_name != 'pull_request' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: artifacts
          # Remove everything to avoid hidden state, i.e., ease debugging.
          # Also, avoids many duplicate figures.
          clean: true
          single-commit: true
          # Deploy artifacts and code, allowing usage of `Pkg.add` at turing.ml.
          folder: .
