name: CompatHelper

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.6]
        os: [ubuntu-latest]
    steps:
      - name: "Install CompatHelper"
        run: |
          using Pkg
          name = "CompatHelper"
          uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
          version = "3"
          Pkg.add(; name, uuid, version)
        shell: julia --color=yes {0}
      - name: "Run CompatHelper"
        run: |
          using CompatHelper
          # TODO: Run for all tutorials once they are updated manually
          # subdirs = [""]
          # for d in readdir("tutorials"; join=true)
          #     if isdir(d) && isfile(joinpath(d, "Project.toml"))
          #         push!(subdirs, d)
          #     end
          # end
          subdirs = ["", "tutorials/00-introduction", "tutorials/01-gaussian-mixture-model", "tutorials/04-hidden-markov-model", "tutorials/08-multinomial-logistic-regression", "tutorials/11-probabilistic-pca", "tutorials/12-gaussian-process"]
          CompatHelper.main(; subdirs)
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
