name: CompatHelper

on:
  schedule:
    # - cron: '00 04 * * 6'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CompatHelper
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add("CompatHelper")

      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}
        shell: julia --color=yes {0}
        run: |
          using CompatHelper
          dir = "tutorials"
          tutorials_dirs = readdir(dir)
          subdirs = joinpath.(dir, tutorials_dirs)
          subdirs = [""; subdirs]
          CompatHelper.main(; subdirs)
