name: Weekly Update

on:
  schedule:
    - cron: 0 0 * * 6
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.UPDATE_MANIFESTS_KEY }}
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - uses: julia-actions/cache@v1
      - name: "Update Manifest.toml files"
        run: find tutorials/ -type f -name Manifest.toml -exec julia --color=yes -e "using Pkg; Pkg.activate(dirname(ARGS[1])); Pkg.instantiate(); Pkg.update()'" {} \;
      - run: git status
      - uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch: 'gh/update_manifests'
          commit-message: 'Update manifest files'
          title: '[UpdateManifests.yml] Update manifest files'
          body: ''
